language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -U pip wheel
  - pip install sphinx
  - pip install 'coverage>=4.0,<4.4'
  - pip install codeclimate-test-reporter
  - python setup.py install
  - python -m nltk.downloader wordnet

script:
  - coverage run --source=. -m unittest discover -s test/

after_success:
  - coverage report -m
  - codeclimate-test-reporter --file .coverage --token $CODECLIMATE_REPO_TOKEN

deploy:
  skip_cleanup: true
  provider: script
  script: bash script/doc_auto_deploy.sh
  on:
    branch: dev-tests

  provider: script
  script: bash script/profile.sh
  on:
    branch: dev-tests


